name: Lint

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Lint RenPy project
      uses: ProjectAliceDev/renpy-lint-action@master
      with:
        sdk-version: '8.1.3'
        project-dir: '.'
    env:
        SDL_AUDIODRIVER: dummy
        SDL_VIDEODRIVER: dummy