name: Lint RenPy

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install RenPy
      uses: PaxlavaGames/renpy-install@v0.1.2
      with:
        version: "8.1.3"
    - name: Lint RenPy
      uses: PaxlavaGames/renpy-lint@v0.1.0