name: Test

on:
  workflow_run:
    workflows: ["Lint"]
    types:
      - completed

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        echo "Install Dependencies"
    - name: Run tests
      run: |
        echo "Run tests...Done"